# Generated by Django 2.1.1 on 2018-09-13 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bloodbank',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
