# Generated by Django 2.1.1 on 2018-09-13 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbb', '0002_auto_20180913_1402'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donors',
            new_name='Donor',
        ),
    ]
