# Generated by Django 2.1.1 on 2018-09-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbb', '0003_auto_20180913_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='donor',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
