# Generated by Django 2.1.1 on 2018-09-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbb', '0006_signup'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Signup',
            new_name='User',
        ),
    ]
